- CHANGELOG.md
- addons/com.heroiclabs.nakama/api/NakamaRTAPI.gd
Custom server logic allows it to return a `matchmaker_matched` without a token and only the `match_id`.
This commit relaxes the requirements of `MatchMakerMatched` schema so it does not fail to parse those cases.
Fixes #14
> Make token in MatchMakerMatched optional.

- CHANGELOG.md
- addons/com.heroiclabs.nakama/api/NakamaRTAPI.gd
- addons/com.heroiclabs.nakama/client/NakamaHTTPAdapter.gd
Threads are not (yet) supported in HTML5 exports, and are in any case not needed since HTTPRequests are always async in browsers.
`MatchData` decode is a bit hacky compared to the rest of the code.
A cleaner solution would probably be to add a condition for that in the serializer, but for just one case it's not worth it.
Should reconsider if more base64 messages needs to be handled.
Fixes #19 
Fixes #18
> Decode base64 data in MatchData, disable use_threads in HTML5.

- addons/com.heroiclabs.nakama/client/NakamaClient.gd
So that you can pass `null` to the username parameter of `update_account_async`:
`client.update_account_async(session, null, ...)`
> Allow updating account without updating username.

- addons/com.heroiclabs.nakama/Nakama.gd
- addons/com.heroiclabs.nakama/api/NakamaAPI.gd
- addons/com.heroiclabs.nakama/api/NakamaRTAPI.gd
- addons/com.heroiclabs.nakama/api/NakamaRTMessage.gd
- addons/com.heroiclabs.nakama/api/NakamaStorageObjectId.gd
- addons/com.heroiclabs.nakama/client/NakamaClient.gd
- addons/com.heroiclabs.nakama/client/NakamaHTTPAdapter.gd
- addons/com.heroiclabs.nakama/socket/NakamaSocket.gd
- addons/com.heroiclabs.nakama/socket/NakamaSocketAdapter.gd
- addons/com.heroiclabs.nakama/utils/NakamaException.gd
- addons/com.heroiclabs.nakama/utils/NakamaSerializer.gd
- codegen/main.go
This PR modifies the doc-comments to allow us to generate a code reference for nakama-godot, using [gdscript docs maker](https://github.com/GDQuest/gdscript-docs-maker).
It changes the doc-comment style from C#-like to GDScript-like, i.e. a plain `# My doc comment`.
Note that I used the latest `apigrpc.swagger.json` file from http://github.com/heroiclabs/nakama to regenerate the GDScript API, so there is one new Facebook-related feature in this commit. Also, there is currently no processing done on a handful of XML tags in the source project, i.e. 
```xml
```
This is in part because we don't have a standard yet for GDScript to document parameters. It might be JS-style in the end, i.e. `@param p_buffer - The buffer with the message to send`, or something else.
> Update main.go, remove XML tags in the GDScript docstrings

- addons/com.heroiclabs.nakama/api/NakamaRTAPI.gd
- addons/com.heroiclabs.nakama/client/NakamaClient.gd
- addons/com.heroiclabs.nakama/client/NakamaHTTPAdapter.gd
client.update_group_async allows updating without name change.
Fix HTTPAdapter _send_async error catching (some times an object, some times a string, some times no error, some times not code).
client.send_rpc_async must have string payload (can be empty).
Fix NakamaRTAPI.Status parsing.
Update list_leaderboard_records_around_owner_async and list_leaderboard_records_async parameter order.
Rename client.JoinTournamentAsync to join_tournament_async.
Fix NakamaClient.send_rpc payload parameter (must be string, can be empty).
Update all p_limit parameters default in NakamaClient to 10.
> Fix default values, error catching, params order.

- CHANGELOG.md
- addons/com.heroiclabs.nakama/api/NakamaRTMessage.gd
- addons/com.heroiclabs.nakama/socket/NakamaSocket.gd
Parameters where swapped, min_count was not assigned.
Fixes #33 .
I was surprised I didn't catch it when making the docs (and testing the doc bits).
Turns out we weren't setting the min count at all (which defaulted to 2) and by chance all the examples never ended up having `min_count > max_count`. Anyway, this fixes it, swapping the parameters, and correctly assigning min_count in MatchmakerAdd.
> Fix add_matchmaker_async/MatchmakerAdd message.

- addons/com.heroiclabs.nakama/api/NakamaRTAPI.gd
`MatchData` currently lacks a `presence` property which lets the receiver verify which player sent a particular state change, a property present in other Nakama clients.
I added this, and it appears to get filled with the correct information, it also displays correctly in the string returned by `_to_string()`
> Add presence property to NakamaRTAPI.MatchData

- CHANGELOG.md
- addons/com.heroiclabs.nakama/Nakama.gd
Fixes: https://github.com/heroiclabs/nakama-godot/issues/40
Adds log level to create_client function call.
I think to improve the elegance of this further would require deeper changes to how the logger reference is passed around.
> Set Log Level

- addons/com.heroiclabs.nakama/client/NakamaClient.gd
- User id requirement when adding friends is not mandatory in the add_friends_async () function in the NakamaAPI.ApiClient class. But it was compulsory in this class.
> Adding friends with only username without id.

- addons/com.heroiclabs.nakama/utils/NakamaSerializer.gd
Adapting variables to new gdscript variable controls.
* If we define a different variable with same name defined from interior indentation areas an error is received in this code in 3.2.2 RC3 version of Godot. This error has been fixed.
> Patch for New gdscript variable controls.

- CHANGELOG.md
- addons/com.heroiclabs.nakama/Nakama.gd
Last week, I spent several hours trying to figure out why sometimes my game wasn't getting messages from a `NakamaSocket` and it turned out that incoming messages won't get processed when the game is paused.
This is because `NakamaSocketAdaptor` polls the WebSocket in it's `_process()` method, that will stop running when the game is paused, because of the pause_mode it and its parents use (the default, `Node.PAUSE_MODE_INHERIT`, which inherits the value used by the root of the tree, which is `Node.PAUSE_MODE_STOP`).
This was especially problematic for my game, as it pauses the game as part of starting a new match (so that it can be sure that every client has completely finished loading before it starts trying to synchronize game state). But this could also cause problems where the user …
> Don't stop processing messages when the game is paused

- CHANGELOG.md
- addons/com.heroiclabs.nakama/client/NakamaClient.gd
`rpc_async_with_key` was always using the GET rpc, while `rpc_async` was always using the POST rpc.
Now they both use the correct HTTP method based on the presence of the payload (if the payload is null, the GET is used, otherwise the POST is used).
Fixes #72.
Closes #69
> Fix rpc_async, rpc_async_with_key.

- CHANGELOG.md
- addons/com.heroiclabs.nakama/client/NakamaHTTPAdapter.gd
Some 2.x versions only had "error" in the dictionary, recent 2.x versions has both "error" and "message", while 3.x versions only has "message".
Closes #68
Fixes #67
> Fix error parsing across Nakama versions.

- CHANGELOG.md
- addons/com.heroiclabs.nakama/api/NakamaAPI.gd
- addons/com.heroiclabs.nakama/api/NakamaSession.gd
- addons/com.heroiclabs.nakama/client/NakamaClient.gd
- codegen/main.go
This is enabled by default, but can be turned off via the `client.auto_refresh` option.
The session is refreshed if it would expire in `client.auto_refresh_seconds` seconds (300 = 5min by default).
This PR depends on #73 .
> NakamaClient now auto-refresh sessions using refresh_token.

- CHANGELOG.md
- addons/com.heroiclabs.nakama/api/NakamaAPI.gd
- addons/com.heroiclabs.nakama/client/NakamaClient.gd
- addons/com.heroiclabs.nakama/client/NakamaHTTPAdapter.gd
- addons/com.heroiclabs.nakama/utils/NakamaAsyncResult.gd
- addons/com.heroiclabs.nakama/utils/NakamaException.gd
- codegen/main.go
In this PR:
- Big refactor of NakamaHTTPAdapter
- Automatic HTTP request retry, with exponential backoff
- Add ability to cancel request in-flight
```gdscript
var req = client.authenticate_device_async("0123456789")
var token = client.last_cancel_token # Get generated token (ID) of the last request.
client.cancel_request(token)
yield(req, "completed") # NakamException("Request cancelled!")
```
Smart features can be configured via:
```gdscript
client.auto_retry = true
client.auto_retry_count = 5
client.auto_retry_backoff_base = 20
```
I'm still wrapping my head around the socket reconnect.
> Implement automatic client retry with exponential backoff.

- CHANGELOG.md
- addons/com.heroiclabs.nakama/utils/NakamaSerializer.gd
- test_suite/tests/socket_multi_test.gd
Fixes #85, where "numeric_properties" were being discarded if using integers. Like I wrote there:
> Normally, in GDScript, ints are silently cast to floats when assigning to a float variable, so it should probably just convert from an int to a float in this case too.
This implements that, converting from ints to floats when a dictionary takes floating-point values.
Also, when I was updating `test_suite/tests/socket_multi_test.gd` to confirm this fix, I noticed that when deserializing "numeric_properties" coming back from Nakama, the values were left as strings! So, this also updates `deserialize()` to convert dictionary values to floats if they are marked as floats in the schema - it was already doing this for ints and bools.
And since `deserialize()` was converting values back to bools …
> Correctly (de-)serialize floats in dictionaries to fix "numeric_properties"

- CHANGELOG.md
- addons/com.heroiclabs.nakama/api/NakamaRTAPI.gd
- addons/com.heroiclabs.nakama/socket/NakamaSocket.gd
- addons/com.heroiclabs.nakama/socket/NakamaSocketAdapter.gd
Per #42, currently, error messages sent by the server and received on the socket are logged (as an "Unhandled response"), but _not_ made available to the developer.
This PR parses those messages and emits them on the "received_error" signal, which is in line with what other client libraries are doing (ex. C# has a "ReceivedError" event for the same purpose).
However, the "received_error" signal already existed, and was previously emitted with integer error codes, when errors occurred while the socket is connecting. This PR, adds a new "connection_error" signal for that purpose.
Because this changes the purpose and signature of the "received_error" signal, it breaks backwards compatibility. An alternative option, would be to leave the "received_error" signal as-is, and add a new signal for …
> NakamaSocket: Emit errors received from the server on the "received_error" signal

- CHANGELOG.md
- addons/com.heroiclabs.nakama/api/NakamaAPI.gd
Added by running the codegen on the Swagger definition from Nakama 3.10.0.
I didn't use the Swagger file from Nakama 3.11.0 due to this issue: https://github.com/heroiclabs/nakama/issues/823
Depending on how that issue pans out, I can make a future PR to update to the Nakama 3.11.0 definition, if needed.
> Expose the "seen_before" property on "NakamaAPI.ApiValidatedPurchase"

- CHANGELOG.md
- addons/com.heroiclabs.nakama/api/NakamaRTMessage.gd
- addons/com.heroiclabs.nakama/socket/NakamaSocket.gd
Fixes #98 
I tested that using a name joins a consistent match ID, that omitting the name will join a unique match ID, and that omitting the name while using an older version of Nakama (I used 3.4.0) will still work fine.
> Add support for creating match by name

- addons/com.heroiclabs.nakama/api/NakamaRTMessage.gd
- addons/com.heroiclabs.nakama/socket/NakamaSocket.gd
- test_suite/tests/socket_party_test.gd
This fixes an issue in `NakamaSocket.add_matchmaker_party_async()` that went unnoticed, in part, because of an issue in the tests for it. This also fixes the tests!
I discovered this while working on the Godot 4 port on PR #103.
> Fix NakamaSocket.add_matchmaker_party_async() and the tests for it

- CHANGELOG.md
- addons/com.heroiclabs.nakama/api/NakamaRTAPI.gd
This must work in Godot 3 due to some automatic type casting. I discovered this while testing in Godot 4, where it isn't automatically casting from string to integer.
> Fix MatchData.op_code type in schema to TYPE_INT

- CHANGELOG.md
- addons/com.heroiclabs.nakama/api/NakamaRTAPI.gd
- addons/com.heroiclabs.nakama/socket/NakamaSocket.gd
The same problem that was fixed for `NakamaRTAPI.MatchState` in #112 exists for `NakamaRTAPI.PartyData`, except that there wasn't an existing method on `NakamaSocket` for sending binary party data. This PR makes it possible to both send and receive binary party data, using the same API as with binary match data.
> Add support for sending and receiving binary data in "NakamaRTAPI.PartyData"

- addons/com.heroiclabs.nakama/utils/NakamaSerializer.gd
A call In `escape_http()` is failing in Godot 4 alpha 14, seemingly due to a name-change from [`to_utf8()`](https://docs.godotengine.org/en/stable/classes/class_string.html#class-string-method-to-utf8) in 3 to [`to_utf8_buffer()`](https://docs.godotengine.org/en/latest/classes/class_string.html#class-string-method-to-utf8-buffer) in 4.
> Fix for Godot String function name change

- addons/com.heroiclabs.nakama/socket/NakamaSocketAdapter.gd
- addons/com.heroiclabs.nakama/utils/NakamaMultiplayerPeer.gd
This updates the NakamaSocketAdaptor to use the refactored WebSocket API in PR https://github.com/godotengine/godot/pull/66594
Leaving as a draft until the refactor is in a Godot 4 beta release, and the changes from PR #134 are merged.
Fixes #137
> Use the refactored WebSocket API

- addons/com.heroiclabs.nakama/api/NakamaAPI.gd
- addons/com.heroiclabs.nakama/api/NakamaRTMessage.gd
- addons/com.heroiclabs.nakama/client/NakamaClient.gd
- addons/com.heroiclabs.nakama/client/NakamaHTTPAdapter.gd
- addons/com.heroiclabs.nakama/socket/NakamaSocket.gd
- addons/com.heroiclabs.nakama/utils/NakamaMultiplayerBridge.gd
- codegen/main.go
- test_suite/run_tests.sh
- test_suite/tester.tscn
- test_suite/tests/client_test.gd
- test_suite/tests/socket_multi_test.gd
- test_suite/tests/socket_party_test.gd
- test_suite/tests/storage_test.gd
In the initial port to Godot 4, I needed to use a whole bunch of hacks and workarounds, due to bugs (mostly in GDScript and mostly concerning typehints). As far as I can tell, all those issues are fixed now (as of Godot 4.0-beta12)!
So, this PR finally removes all the hacks and workarounds :-)
A side-effect of this is that the code for Godot 3 and 4 is now slightly closer together, which will make porting changes between the two versions a little easier.
> Remove hacks for GDScript bugs that are fixed as of 4.0-beta12

- CHANGELOG.md
In preparation for releasing the Godot 4 version of the addon, this just synchronizes the CHANGELOG.md with the Godot 3 version. Not sure how they got out of sync - I must have accidentally left out the CHANGELOG.md change when porting one of the PRs to Godot 4.
> [godot-4] Synchronize CHANGELOG.md with the Godot 3 branch

- CHANGELOG.md
- addons/com.heroiclabs.nakama/api/NakamaAPI.gd
- addons/com.heroiclabs.nakama/client/NakamaClient.gd
- codegen/main.go
There is a small problem with the apigrpc.swagger.json in Nakama v3.15.0 - I created an issue for it:
https://github.com/heroiclabs/nakama/issues/976
So, in this PR, I just didn't include the changes that the code generator made for the incorrect data in the swagger definition. Once that issue is fixed, the code directly from the code generator should match what is included here.
> Add support for delete_account_sync() and other API changes that were added in Nakama v3.15.0

- CHANGELOG.md
- addons/com.heroiclabs.nakama/api/NakamaAPI.gd
- addons/com.heroiclabs.nakama/client/NakamaClient.gd
- codegen/main.go
This is the Godot 4 version of PR #146
> [Godot 4] Add support for delete_account_sync() and other API changes that were added in Nakama v3.15.0

- addons/com.heroiclabs.nakama/client/NakamaHTTPAdapter.gd
Updates call to `HTTPRequest.request` to be compatible with Godot beta 17
> fix: correct call to request for beta17

- addons/com.heroiclabs.nakama/utils/NakamaMultiplayerPeer.gd
In the `NakamaMultiplayerPeer` class, updates the typing in the signatures of the `_get_connection_status` `_get_transfer_mode` and `_get_transfer_mode` functions.
They return enums or have them as arguments and are typed as int which causes errors in godot 4.0 rc1.
For consistency, the typing of the `_connection_status` variable has also been updated (letting it typed as an int does not give an error).
> Fix typing where enums are involved for rc1

- addons/com.heroiclabs.nakama/utils/NakamaAsyncResult.gd
- addons/com.heroiclabs.nakama/utils/NakamaMultiplayerPeer.gd
Godot introduced a new function `is_instance_of` to check if an Object is a type that is not known at runtime. This breaks functionality using `is` to check types not known at runtime. `_put_packet_script` function has also been updated to return `Error` instead of `int` to match parent function.
> Godot 4 RC3 Type check and return fixes

- addons/com.heroiclabs.nakama/mono-utils/GodotHttpAdapter.cs
Changed `GodotHttpAdapter.SendAsync` to send an empty body string if the byte array is null. Originally it would throw an error because `System.Text.Encoding` cannot encode a null byte array.
Fixes #161
> Fix byte array null error in GodotHttpAdapter

- addons/com.heroiclabs.nakama/client/NakamaHTTPAdapter.gd
I've reported this on the forums a while ago, but there seems to have been a small typo in the `NakamaHTTPAdapter.AsyncRequest` `parse_result()` method,
where it should have been
```gdscript
json_error
```
instead of 
```
json.error
```
which resulted in an error message.
The reason the issue occurred is because the `json.parse()` method worked differently in Godot 3.x, and the code probably wasn't updated when migrating to Godot 4.
I've also included the JSON error message in the logger text to make debugging a bit easier.
> Fix JSON error typo in NakamaHTTPAdapter

- addons/com.heroiclabs.nakama/api/NakamaAPI.gd
- addons/com.heroiclabs.nakama/api/NakamaRTAPI.gd
Godot 3 does not support classes referencing their own class type *inside* their own functions. Using the `is` keyword in combination will throw a parser error. But using the `as` keyword similarly does not. Its apparent downstream affect is at least reports of memory leaks.
I have tagged #57 in an associated Godot repo issue and appealed for a Godot maintainer to target Godot 3.6 as it was targeted to Godot 3.5, proposing a solution to guard against this usage of `as`, as it's unlikely to receive the circular dependency enhancement that Godot 4 received--this nakama-godot issue *does not* reproduce with Godot 4.
> Removed code which causes Godot 3 to report memory leaks (#57)

- addons/com.heroiclabs.nakama/dotnet-utils/GodotHttpAdapter.cs
Change HTTPRequest -> HttpRequest to match Godot's new naming.
Change .Request call to contain 4 args to match new Godot signature for HttpRequest.Request
> Update Symbol Names to match Godot, Fix Request Call Args

- addons/com.heroiclabs.nakama/Nakama.gd
- addons/com.heroiclabs.nakama/Satori.gd
- addons/com.heroiclabs.nakama/Satori/Event.gd
- addons/com.heroiclabs.nakama/Satori/SatoriAPI.gd
- addons/com.heroiclabs.nakama/Satori/SatoriClient.gd
- addons/com.heroiclabs.nakama/Satori/SatoriHttpAdapter.gd
- addons/com.heroiclabs.nakama/Satori/SatoriSession.gd
- addons/com.heroiclabs.nakama/Satori/utils/SatoriException.gd
- addons/com.heroiclabs.nakama/api/NakamaAPI.gd
- addons/com.heroiclabs.nakama/api/NakamaRTAPI.gd
- addons/com.heroiclabs.nakama/api/NakamaRTMessage.gd
- addons/com.heroiclabs.nakama/api/NakamaStorageObjectId.gd
- addons/com.heroiclabs.nakama/client/NakamaClient.gd
- addons/com.heroiclabs.nakama/client/NakamaHTTPAdapter.gd
- addons/com.heroiclabs.nakama/socket/NakamaSocket.gd
- addons/com.heroiclabs.nakama/socket/NakamaSocketAdapter.gd
- addons/com.heroiclabs.nakama/utils/NakamaException.gd
- addons/com.heroiclabs.nakama/utils/NakamaMultiplayerBridge.gd
This PR converts all `#comment` to `##comment` so that can appear inside help
> convert comments to document
