heroiclabs/nakama-godot

CHANGELOG.md
addons/com.heroiclabs.nakama/api/NakamaRTMessage.gd
addons/com.heroiclabs.nakama/socket/NakamaSocket.gd

Slightly better logs.
Fixes #16 .

Fix op_code/data format in send_match_state[_raw]

---

CHANGELOG.md
addons/com.heroiclabs.nakama/api/NakamaSession.gd
test_suite/tests/client_test.gd

Also add it to tests.
As reported here https://github.com/heroiclabs/nakama-godot/issues/21#issuecomment-588211132

Fix NakamaSession.is_expired

---

addons/com.heroiclabs.nakama/client/NakamaClient.gd

Parameter was missing, only allowing public objects listing.

Fix list_storage_objects_async for user id.

---

addons/com.heroiclabs.nakama/client/NakamaClient.gd

Fix FacebookInstantGame endpoints.

---

addons/com.heroiclabs.nakama/api/NakamaRTAPI.gd

No descriptor field, new subcontext field.

Update RTAPI Stream parsing.

---

CHANGELOG.md
README.md

Getting ready for 2.0.0 release.
Major verison bump due to broken compatiblity.

Update CHANGELOG, README.md

---

CHANGELOG.md
addons/com.heroiclabs.nakama/api/NakamaRTAPI.gd
addons/com.heroiclabs.nakama/socket/NakamaSocket.gd

Also fix styling in previous commit, add CHANGELOG info.
Fixes #38

Fix received_error signal.

---

CHANGELOG.md
addons/com.heroiclabs.nakama/utils/NakamaSerializer.gd
test_suite/tests/socket_multi_test.gd

Fix dictionary serialization.

---

CHANGELOG.md
addons/com.heroiclabs.nakama/client/NakamaClient.gd

Also amend the changelog since we are at it.

Fix session_logout_async merge error.

---

addons/com.heroiclabs.nakama/api/NakamaAPI.gd
codegen/main.go

Fix code generation for query paramaters - use snake case.

---

CHANGELOG.md
addons/com.heroiclabs.nakama/client/NakamaClient.gd

Make it possible to omit the label and query on NakamaClient.list_matches_async().

---

CHANGELOG.md

Nakama Godot 3.0.0 release

---

CHANGELOG.md
addons/com.heroiclabs.nakama/api/NakamaRTAPI.gd
addons/com.heroiclabs.nakama/socket/NakamaSocket.gd

Fix receiving "NakamaRTAPI.PartyClose" close message

---

CHANGELOG.md
addons/com.heroiclabs.nakama/api/NakamaRTAPI.gd
addons/com.heroiclabs.nakama/socket/NakamaSocket.gd

Fix PartyData serialization and deserialization by using base64.
Fixes https://github.com/heroiclabs/nakama-godot/issues/101

Fix PartyData serialization and deserialization by using base64.

---

test_suite/tests/socket_multi_test.gd
test_suite/tests/storage_test.gd

After these changes the test suite passes on Godot 4.0-alpha9!

Additional fixes for test suite

---

CHANGELOG.md
addons/com.heroiclabs.nakama/Nakama.gd

Fix circular reference in Nakama singleton to itself

---

CHANGELOG.md
addons/com.heroiclabs.nakama/utils/NakamaMultiplayerBridge.gd
addons/com.heroiclabs.nakama/utils/NakamaMultiplayerPeer.gd

This is the Godot 4 version of PR #116

[godot-4] Add NakamaMultiplayerBridge to integrate with Godot's High-Level Multiplayer API

---

README.md

Add notes to the README about HLMP integration and Godot 4

---

README.md

This is the Godot 4 version of #129

Add notes to the README about HLMP integration and Godot 4 (Godot 4 version)

---

CHANGELOG.md
addons/com.heroiclabs.nakama/client/NakamaClient.gd

I noticed that we were missing this when reviewing the Godot snippets in the documentation. I'm not entirely sure how/why this got skipped originally, but it's simple enough to add :-)

Add support for sending events

---

addons/com.heroiclabs.nakama/utils/NakamaMultiplayerPeer.gd

Over the last couple of weeks, there's been a number of refactors done to Godot 4's multiplayer API. This PR accommodates those changes!

Update NakamaMultiplayerPeer for latest changes to Godot's multiplayer API

---

CHANGELOG.md
addons/com.heroiclabs.nakama/client/NakamaHTTPAdapter.gd

Allow disabling threads for making HTTP requests

---

CHANGELOG.md
addons/com.heroiclabs.nakama/client/NakamaHTTPAdapter.gd

[godot-4] Allow disabling threads for making HTTP requests

---

addons/com.heroiclabs.nakama/dotnet-utils/GodotHttpAdapter.cs

This is the Godot 4 version of #162 which fixes #161
Code by @Atlinx

Fix null byte array error in GodotHttpAdapter for C# (Godot 4)

---

addons/com.heroiclabs.nakama/api/NakamaAPI.gd
addons/com.heroiclabs.nakama/api/NakamaRTAPI.gd
addons/com.heroiclabs.nakama/client/NakamaClient.gd

I don't know exactly what happened, but the merge commit from https://github.com/heroiclabs/nakama-godot/pull/173 didn't go exactly as it should have.
It appears to have auto-resolved some merge conflicts such that both the Godot 3 & 4 versions of some changes are present.
This PR removes the left over Godot 3 code that shouldn't be there!

Fix some things that went wrong in the Godot 4 merge commit

---

addons/com.heroiclabs.nakama/utils/NakamaMultiplayerPeer.gd

Changed `int` return type on _get_packet_mode() to instead return `TransferMode` enum.

Changed from int to TransferMode

---

README.md

Corrected some broken links to the Nakama documentation I noticed.

Fixed links to nakama-server documentation

---

addons/com.heroiclabs.nakama/Satori/Event.gd
addons/com.heroiclabs.nakama/Satori/SatoriClient.gd
addons/com.heroiclabs.nakama/Satori/SatoriHttpAdapter.gd
addons/com.heroiclabs.nakama/Satori/utils/SatoriSerializer.gd

Includes following APIs:
• Authenticate & Logout.
• Session refresh.
• Send events.
• Experiments.
• Flags (default flags coming in separate PR).
• Live events.

Add Satori Client APIs

---

addons/com.heroiclabs.nakama/Satori/SatoriClient.gd
addons/com.heroiclabs.nakama/Satori/SatoriHttpAdapter.gd
addons/com.heroiclabs.nakama/Satori/SatoriSession.gd
addons/com.heroiclabs.nakama/Satori/utils/SatoriAsyncResult.gd
addons/com.heroiclabs.nakama/Satori/utils/SatoriLogger.gd
addons/com.heroiclabs.nakama/client/NakamaClient.gd
addons/com.heroiclabs.nakama/socket/NakamaSocketAdapter.gd
addons/com.heroiclabs.nakama/utils/NakamaAsyncResult.gd
addons/com.heroiclabs.nakama/utils/NakamaLogger.gd
addons/com.heroiclabs.nakama/utils/NakamaMultiplayerPeer.gd

I noticed that there were places that did not have typing so I added them. I was thinking of adding typing everywhere, but it looks like some places might need a bit of refactoring to properly add typing, so I am currently thinking of dividing it into multiple PRs.

chore: Added typing
